### ISSUE TITLE
Chat window opens randomly

### ISSUE THREAD

**Issue by shanefisher** [muchino/confluence.chat#86] opened 2014-03-13 20:25 UTC
We are finding that when you have a conversation with someone and then you close the conversation window that it will jump open at a later point somewhat randomly. I am not sure what behaviour causes the window to open but to avoid the frustration of having to close the window over and over again I suggest it should only open if there is a new comment or the user opens it manually. Observed this behaviour on both PC and Mac.

**Comment by apirchmoser** [comment] 2015-08-10 12:19
Same behaviour  - Confluence 5.8.5 and Chat 2.0.6 , but the problem appreared with older versions too.
Let me know if you want frutehr info on the chat settings

**Comment by muchino** [comment] 2015-08-12 18:19
the issue is, that I can't reproduce this issue. and I have no idea what you can give me :(

**Comment by apirchmoser** [comment] 2016-01-29 08:39
@shanefisher: Are you still facing this issue? We could compare the list of plugins installed to find if it could be a conflict. Br, Anne

**Comment by muchino** [comment] 2016-02-18 20:23
It would be cool if you could update this if you find some reason, but for the moment I close the issue

**Closed by muchino** 2016-02-18 20:23 UTC
